### PR TITLE
Localization support for messages

### PR DESCRIPTION
**Pull request by TTimeGaming**
Added support for localization of displayed messages

### CODE REVIEW

**Comment by kaelad02** [comment]
Sorry for the delay on this. What is the use case for this? Why the need for externalized, localized messages? I ask mainly since that requires some coding, adding localization files to your world or a module in order to use this. Something I don't suspect most people will do.

**Comment by TTimeGaming** [comment]
It is quite situational but allows for module developers to include localization support. Definitely wouldn't receive that much usage, so definitely low usage. I just like being able to add locale support where I see it can be done 👍

**Comment by kaelad02** [comment]
Did you make a module that would use it?

**Comment by TTimeGaming** [comment]
Just the beginning stages of some work. Looking at compatibility where applicable of other 5e modules and the possibility of localisation here came up.

**Pull request closed without merging**
