### PR TITLE
resolves #3 New conditional message feature

### LINKED ISSUE #3: [FEATURE] Consider supporting advantage with a condition
Hello,

Some items & features grant advantage, but only on certain conditions.

For example:  `Keen Smell. The tiger has advantage on Wisdom (Perception) checks that rely on smell.`

Maybe this module can implement some kind of reminder about that?
Since we can't automate this, possibly a simple chat message? Or a message before rolling?

### PR DESCRIPTION
**Pull request by kaelad02**
Implement the new feature to add conditional messages to die rolls. See #3 for all the details. Some notes about this implementation:

1. Will show multiple messages and uses the active effect's `priority` field to order them
2. Formats the messages as a block with a similar look to the input fields on the dialog
3. Uses `Hooks.once` to add messages to the next roll dialog that pops up. There is a known issue, however, if multiple rolls are called at the same time (e.g. roll saving throw on multiple tokens) that don't `await` on each roll. The Saving Throw button on a spell's chat card will work fine since it uses `await` on each call. However, a macro may not and Token Action HUD does not either. Using either of the latter will result in all the roll dialogs being fired at once and the messages aren't added to the correct dialogs.

Some screenshots to illustrate what it looks like. We don't have to get the styling perfect now since we an always update the CSS later. But if there's something glaring we should fix it sooner rather than later.

### Dwarven Resiliance

```
key: flags.adv-reminder.message.ability.save.all
value: <b>Advantage</b> on saving throws against poison
```

image

### Two messages

```
key: flags.adv-reminder.message.all
value: <b>Note:</b> some reminder on every roll
priority: 1

key: flags.adv-reminder.message.ability.save.all
value: <b>Advantage</b> on saving throws against poison
priority: 20
```

image

### CODE REVIEW

**Comment by kaelad02** [comment]
I'm torn on the hooks problem. On one hand, we could fix the issue by doing what you did in #9 but it seems like workaround. The easier fix would be on the caller's end (i.e. the macro or Token Action HUD) to `await` on each call rather than launch them all at the same time. I'm not sure I like kicking the can and making it someone else's problem either.

**Comment by kaelad02** [comment]
Just saving this macro here I used to test the hooks issue.

```js
const targets = canvas.tokens.controlled;
for (const token of targets) {
  const speaker = ChatMessage.getSpeaker({ scene: canvas.scene, token });
  await token.actor.rollAbilitySave("dex", { event, speaker });
}
```

**Comment by DarKDinDoN** [comment]
> I'm torn on the hooks problem. On one hand, we could fix the issue by doing what you did in #9 but it seems like workaround. The easier fix would be on the caller's end (i.e. the macro or Token Action HUD) to `await` on each call rather than launch them all at the same time. I'm not sure I like kicking the can and making it someone else's problem either.
> 
> @DarKDinDoN what do you think?

Hmm, I think the issue runs deeper than simply awaiting calls.

There are items configured with templates. In this case, I think the roll dialog is delayed until the template is placed on the canvas (which is a hook). Or at least some useful modules do. `await` won't work in this case.

Also, some modules or maybe even the core 5e runs command through the GM. Same issue. `await` won't work as well.

I was hoping for a better solution than the `renderDialog` DOM id hack as well.

**Comment by DarKDinDoN** [comment]
Probably a module then.

I'm sensing the same vibe as for the "priority" feature or the implementation of tests.  It seems to me that you are looking for the "perfect" way of coding, which is not a bad. Good code is good code. But, in my experience, it actually gets in the way of features or code simplicity (too much separation, abstraction, etc.).

Not judging, you do you, and that's quite alright. Just me telling you that you're overthinking, and obviously you do whatever you want.
Such a module is not a life achievement goal, just a foundry module. You don't need it to be perfect by the coding standards :)

Also, two choices here:
- You either implement the fix, and you probably won't remember it in a few days
- Or ask ppl like me (as a fvtt user) in need of this, to demand module developers to change their module

I obviously prefer the latter.
But I don't  think there is a better solution.
You are trading ease of use for those using modules established before yours for stability, not hacky and core compatible code.
Once again, your call.

**Comment by kaelad02** [comment]
That's fair. I was considering merging it as-is and mark it as a known issue. Then keep digging into it further, looking for another solution. But at some point, if I couldn't find anything better then I'd go with what you came up with. I'm trying to avoid letting the perfect be the enemy of the good. If there really isn't any better way out there, then the ID method it is.

For the priority thing, I initially thought it was a clever way to order things. Then I looked at it again and wondered if it was a bad idea to use it that way since it's not _exactly_ what priority was put there for. Just used to the environment at work where I can talk this stuff out with coworkers as opposed to it being out in the public like this. Sometimes I just have to explain it out loud to someone just to end up figuring it out myself. Still adjusting to a different way of doing it.

I'll put the ID method in, update the README/CHANGELOG and cut a release. Considering it's adding something new/big, might be worthy enough to bump up to v1.0

**Comment by kaelad02** [comment]
It's the same basic approach, but I can also just put the message content in the `dialogOptions` instead of a generated ID. Same basic idea, but just putting the payload directly there instead of an ID to match.

**Comment by DarKDinDoN** [comment]
@kaelad02 I thought about that.
The issue is that the way 5e system is coded, only a subset of the option object gets passed to the dialog. Not the entire object.

Also, about the grant message.
I found an example on damages. The spell Hunter's Mark applies a mark on an enemy. On, yhe PC adds 1d6 to the damage roll.
I think he can be a great example for the "grant message" feature, so the user don't forget this. (even tho it is displayed to everyone, I think other players can simply ignore the message).

**Comment by kaelad02** [comment]
If it goes in the `dialogOptions` part it looks like it gets passed all the way through. But in any case, I'll check that out later. Same for the grant message part, I'll add that in later.

I tested it with Token Action HUD and my macro and seems to put the right messages on the right dialogs.

**Comment by DarKDinDoN** [comment]
Ah yes. My Bad. dialogOptions gets passed all the way through.

I'll test that when the next release is out.

**Comment by kaelad02** [comment]
> If I'm not mistaken: for damage roll, the data structure is actually options.options.dialogOptions

I see what you mean. Ugh

**Comment by kaelad02** [comment]
Thanks for testing the damage rolls. Also got me thinking about MRE and tried there and found out it doesn't work for damage rolls if you get the dialog prompt. MRE re-implements the damage dialog code from the core roller but it doesn't pass along any options so I can't modify it. So I added a note about it in the readme.

**Comment by kaelad02** [comment]
I'll update and check. @DarKDinDoN Is everything else okay?

**Comment by DarKDinDoN** [comment]
Also, you can now add the effect label quite easily `change.document.data.label`.
I suggest adding this at the end of each message between `[]` (`()` are generally used in texts, and we don't want to confuse ppl).
Maybe add a setting if you don't want this by default.

**Comment by kaelad02** [comment]
> Also, you can now add the effect label quite easily `change.document.data.label`.

I understand why you had this in your version but I'm not sure it's necessary now. When you had it tied to advantage or disadvantage, the user didn't have a choice on the formatting so including the source made sense. Now that it's just a message tied to a particular roll, the user can format it however they like. If they want to include the source name at the beginning, end, or not at all is up to them.

Using keen smell as an example, I could see either of these as viable ways to present it:

- **Keen Smell.** Advantage on checks that rely on smell.
- **Advantage** on checks that rely on smell. [Keen Smell]

**Comment by DarKDinDoN** [comment]
> I understand why you had this in your version but I'm not sure it's necessary now. When you had it tied to advantage or disadvantage, the user didn't have a choice on the formatting so including the source made sense. Now that it's just a message tied to a particular roll, the user can format it however they like. If they want to include the source name at the beginning, end, or not at all is up to them.

Absolutely, it's not about the user being able to do it himself. It's about the module being helpful in the message creation.
Having to type all the effect labels and retype them if the effect label changes, it's kind of cumbersome. More about UX than features.
That is why I was suggesting it as an option. To make life easier for ppl who want this.

**Comment by DarKDinDoN** [comment]
Another method worth considering is having a little helper for the user.
Like parsing a variable and using the localization module to handle it easily.

In the effect change value: `{label}. This is my message.`
In the template `<div class="adv-reminder-message">{{{localize value label=label}}}</div>` where value is the message and label the effect label.
Would result into `Keen smell. This is my message.`

Tested on my end, seems ok.
The only possible issue is if the user type a message that corresponds to a localization key. But I highly doubt it will happen since all the i18n keys tend to be namespaced.

**Comment by kaelad02** [comment]
>Another method worth considering is having a little helper for the user.
>Like parsing a variable and using the localization module to handle it easily.

I read this in the morning then by the time I tried it out I was doing something different. Your previous suggestion was to put the active effect name (well, technically `label`) at the end. This I read this version that had it at the beginning and it reminded me of how features are displayed in the monster stat blocks and other places:

**Feature Name.** A description of the feature.  
e.g.  
**Keen Smell.** Advantage on checks relying on smell.  
**Pack Tactics.** Advantage if at least one ally is adjacent to the target.

I kind of like that idea and it only took two small changes, seen here: e98e670f4e981a450caf020a915aaeb836910cf5

Now that version changes the format and removes any use of HTML tags in the value. I don't like the idea of a breaking change but I really do like the look of it because of how similar it is to the presentation of features.

**Comment by DarKDinDoN** [comment]
I kind of like the localization method.
This way, you don't impose a format on ppl.

For example, What is best?

- **Keen Smell**. Advantage on checks relying on smell.
or
- **Advantage**: on checks relying on smell [Keen Smell]

I guess it depends on the user. But I think that a player is more interested in the overall effect than the actual effect label (even tho the effect label is an interesting piece of information)

As an example (sorry for the french writing), one of my player has this configuration on the survival check:
image

The downside of this is the formatting, although imposing formatting is also not great imo, users have to know a bit of HTML, and it's a bit more cumbersome.

Once again, I'm not really sure one solution is that better that the other. But I prefer the loalization part.
Also, this is a two-line feature as well.

**Comment by DarKDinDoN** [comment]
Or both?
I mean, no `{label}` found in the value, then we use the default formatting.
If found, applying the localization method.

This way, we have a decent default formatting and customization if needed.

**Pull request merged**
