### PR TITLE
Feat custom adv disadv

### PR DESCRIPTION
**Pull request by DarKDinDoN**
Hello,

This is my attempt to solve: https://github.com/kaelad02/adv-reminder/issues/3
Although, I'm stuck. Maybe you can find a solution (see below).

**1st Commit: Localization**
Simple localization. Not much to say.

**2nd commit: Compatibility with MRE**
Just a simple change for this module to be compatible with MRE (https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E).
MRE, like this module, is low automation oriented. It just fast-forwards rolls. This change is to catch the MRE fast-forwards (with a `fastForward` property added by MRE in the options object)

**3rd Commit: Store and retrieve custom flags**
The good stuff. Basically, all keys that are existing also exist with the prefix `custom.`
If such a key is found in the actor's effects and also has a value, then it is added to an array.

There are 4 arrays:
- customAdvantages
- customDisadvantages
- customCrits
- customNormals

Those 4 arrays are then sent as part of the `options` object of the roll.

Note that I changed the naming of a few variables and method to better reflect the overall features.
Also, I prepare the origin actor effects object with more than just the keys, but also the value of a change and the label of the parent effect (so we can display all of that in the 5e Roll Dialog)

**The "help, I'm stuck" part: getting FVTT to display the custom flags**
So, the objective is to display the custom flags like this:

image

I've tried two ways of doing it:
1. Wrapping/overriding 5e class/methods/functions. Well, beside overriding a tone of 5e methods (yuck), I'm not even sure this is possible. Some functions that are part of the process are not even exposed by the system (correct me if I'm wrong).
2. Using the `Hook.once("renderDialog", () => {})` to catch the next dialog opened. Working great, until two windows opens at the same time. That happens in rare cases, but it still happens. And when it happens, it goes "boum".

So, I'm now stuck on that part. Maybe you can take a shot at it? Fresh eyes might solve the puzzle.

In case, you need this.
Here is the added template part I used for the roll window:
```handlebars
<form>
    [...]
    <div class="custom-flags">
        {{#if customAdvantages}}
            <ul>
                {{#each customAdvantages}}
                    <li><b>{{ localize "DND5E.Advantage" }} :</b> {{ value }} ({{ label }})</li>
                {{/each}}
            </ul>
        {{/if}}
        {{#if customDisadvantages}}
            <ul>
                {{#each customDisadvantages}}
                    <li><b>{{ localize "DND5E.Disadvantage" }} :</b> {{ value }} ({{ label }})</li>
                {{/each}}
            </ul>
        {{/if}}
        {{#if customCrits}}
            <ul>
                {{#each customCrits}}
                    <li><b>{{ localize "DND5E.CriticalHit" }} :</b> {{ value }} ({{ label }})</li>
                {{/each}}
            </ul>
        {{/if}}
        {{#if customNormals}}
            <ul>
                {{#each customNormals}}
                    <li><b>{{ localize "adv-reminder.no-critical" }} :</b> {{ value }} ({{ label }})</li>
                {{/each}}
            </ul>
        {{/if}}
    </div>
</form>
```

The CSS that goes with it:
```css
.dialog .dialog-content div.custom-flags {
    font-size: 12px;
    margin: 10px 0;
    padding: 5px;
    border: 1px solid rgb(0, 0, 0, 0.2);
    background-color:rgb(0, 0, 0, 0.05);
}

.dialog .dialog-content div.custom-flags ul:not(:first-child) {
    border-top: 1px solid rgb(0, 0, 0, 0.2);
    padding-top: 6px;
}
```

And the localization keys:
```
[EN] "no-critical": "No critical"
[FR] "no-critical": "Critique impossible"
```

Hope you can make something of this!

### CODE REVIEW

**Comment by DarKDinDoN** [comment]
Hello,

Found a solution. Hacky, but surprisingly robust (couldn't break it).

**4th & 5th commit: merging the tests**
And modifying the data structure to reflet the changes in this PR

**6th commit: Display custom flags in roll dialogs**
Back to the first option: using the `rollDialog` hook. Previously, I add a success with this method but couldn't handle multiple dialogs opened almost simultaneously.

So, I'm now generating a `randomID` that I pass as the dialog window DOM id, using `options.dialogOptions.id` or (`options.options.dialogOptions.id` in the rollDamage case).

Until the callback function doesn't match the dialog window DOM id with the `randomID` generated, it does nothing.
As soon as there is a match, the dialog is updated and the callback unregisters itself from the hooks chain.

This way, even if multiple windows are opened before the window that should be updated is displayed, the callback does actually nothing. And once we hit the callback with the right ID, the window is updated and the hook is unregistered.
Maybe we should add a safeguard in case the hook is never unregistered (never got a match on the DOM id). In theory, if there is a Hook created, there will be a corresponding dialog rendered (should always be the case).

This method as a serious advantage: no more wrapping/overriding 5e methods/classes.

**Comment by DarKDinDoN** [comment]
**Last commit: renderDialog Hook safegard**
If `options.dialogOptions.id` or `options.options.dialogOptions.id` are not supplied (early `return` in some `updateOptions` methods), then no hook is created.

If a hook is created but not unregistered 10 seconds after creation. It is automatically unregistered.

**Comment by kaelad02** [comment]
Sorry, didn't get a chance to really look at it yesterday. The message part looks a lot more complicated than I think it needs to be. I had worked on it earlier in another branch but didn't push it until now. I got distracted with other things and haven't looked at it in a few days. The branch name is `conditionalMessage` and the bulk of the implementation is in the new `messages.js` file.

I defined new keys that mirrored the advantage/disadvantage keys that we already use. So for example, if you wanted advantage on Constitution Saving Throws then you'd use `flags.midi-qol.advantage.ability.save.con`. If you wanted a message to appear on the same roll (e.g. for dwarven resilience) then you'd use `flags.adv-reminder.message.ability.save.con` with a value like `Advantage on saving throws against poison`. Basically replacing `midi-qol` with `adv-reminder` and `advantage` with `message`.

But to show it I do hooking similar to what you did but I just used `Hooks.once` so it only calls my custom code once. Seemed to work for me, but I'm currently testing in a world with very little modules running.

**Comment by kaelad02** [comment]
And regarding the unit tests...
I added those in, partially as an exercise to learn how to do unit testing with Node.js. But I also planned on switching the code from reading the effects to applying them to the actor data and reading that, like DAE and Midi QOL do. It appears that effect changes are applied to the actor data anyways, just need some special handling when you choose the Custom change mode and from what I can tell it's just a few lines anyways.

Working on another local branch, I started making those changes to the reminders and it looks fine. I did, however, run into an issue on the fails because it prints a failure message with originating active effect in the chat message. I don't want to bog this PR down with how the fail message looks, but wanted to bring it up since you were including the active effect label in the message.

Changing everything over to read the actor data would remove the source of the change (i.e. the active effect's name/label). Is it the end of the world?

**Comment by kaelad02** [comment]
I do like your idea of multiple messages being there instead of mine just looking for the first

**Comment by DarKDinDoN** [comment]
@kaelad02 Hey, thx for looking into this PR.

I really like the fact that your implementation doesn't tie custom messages with advantages/disadvantages/crits.
And yes, I agree that my message is a lot more complicated than your implementation.  It's due to the fact that I was trying to tie everything to advantages/disadvantages/crits, so I needed a clear distinction between advantages, disadvantages and crits.
Anyway, your idea is much better.
Also, priority sorting is a nice feature.

I installed your branch, and here are my thoughts:
- The way you are handling the hooking was what I did at first. It works until multiple roll dialogs are shown at the same time. The problem is due to the render time of the roll dialog. If you initiate the render of a dialog and initiate a second, the order of rendering is not guarantee and not sequential. Thus ending up with messages in the wrong roll dialog. You can take a look at how I handled that. (i.e: multiple players making a save roll at the same time, or multiple roll dialogs opened by the same player at once with smt like "Token HUD actions" )
- As stated, you display only the first message found. You could display all the messages found in an unordered list.
- The ability to display a message in the damage roll window is missing
- Just a touch of styling would be pleasant. Default font size is too big. Not much you can write in a single line.
- The original effect label is not mandatory indeed. We can easily spare it 
- I suggest a feature allowing the user to emphasize some words. Just the beginning of the message. Like the message `"Title.|this is the description"` would translate in ➡️ "**Title**. this is the description".

Would you mind merging this as well? https://github.com/kaelad02/adv-reminder/pull/9/commits/cf5f783a2ca87357138444dd4084d814aed48563
It's just a compatibility fix for MRE (https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E). MRE, like this module, is low automation oriented. It just fast-forwards rolls. This change is to catch the MRE fast-forwards (with a `fastForward` property added by MRE in the options object)

**Comment by kaelad02** [comment]
The MRE compatibility fix, is that related to ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E#22? I kept searching for `fastForward` but didn't find it in MRE's code. I eventually found that recent PR.

**Comment by DarKDinDoN** [comment]
@kaelad02 https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/blob/master/scripts/patches/ability-check-patches.mjs#L51

Never trust the GitHub search feature. It simply doesn't work like your IDE and sometimes, it doesn't work at all.

**Comment by kaelad02** [comment]
Thanks for all your help with this feature, especially the fix for getting the messages to appear on the right dialog when multiple saves occur at the same time. I was going to also grab your localization fix but I'm considering changing the fail chat message to look more like a roll dialog. The fail message is okay, but I think it could be better. Thanks again.

**Comment by DarKDinDoN** [comment]
You are welcome.
Thank you to come up with this wonderful idea for a module.
Bery helpful!

**Pull request closed without merging**
